# Generated by Django 4.1.2 on 2022-10-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_rename_routine_day_day_rename_routine_result_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(max_length=100),
        ),
    ]
